### ISSUE TITLE
ldap.schema.tokenizer.extract_tokens() uses dict.has_key()

### ISSUE THREAD

**Issue by HonzaCholasta** [pyldap/pyldap#10]
The extract_tokens() function of the ldap.schema.tokenizer module uses has_key() method on dict, which is not available in Python 3.

**Comment by hroncok** [comment]
Should be replaced by `key in dict` statement.

I can see `result_has_key = result.has_key` in [here](https://github.com/pyldap/pyldap/blob/master/Lib/ldap/schema/tokenizer.py#L58) and I am not quite sure why is this used, but either we can remove it and replace both `if result_has_key(l[i])` with `if l[i] in result`, or we can redefine `result_has_key` as `lamba k: k in result`.

Does anyone know why is there the `result_has_key` definition?

**Comment by rkuska** [comment]
It's optimization. It should be safe to replace with `in` calls as there is no function call overhead.
