### ISSUE TITLE
Release 2.4.36

### ISSUE THREAD

**Issue by encukou** [pyldap/pyldap#102]
Lots of work went into python-ldap 2-4-36, but since it's mostly test refactoring, I don't think we need to make a pyldap just from it.
However, there are some new pyldap-specific changes in master – most notably @darkrain42's patch for unicode handling in Python 2 (#95). So, if there are no objections, I'd like to release 2.4.36 soon.

**Comment by rbarrois** [comment]
Sounds good to me :)

Thanks for this!

**Comment by encukou** [comment]
pyldap 2.4.36 is ow on [PyPI](https://pypi.python.org/pypi/pyldap/2.4.36). Thank you to all contributors!
