### ISSUE TITLE
Release 2.4.37

### ISSUE THREAD

**Issue by encukou** [pyldap/pyldap#107]
As with [2.4.36](https://github.com/pyldap/pyldap/issues/102), I'd like to release 2.4.37 soon.
Upstream only refactored tests (plus added a fix we have backported already), but there are pyldap-specific fixes (#99, #105).

If https://github.com/pyldap/pyldap/pull/105 doesn't get a review by then, I'll go ahead and include it: the non-test changes there are trivial.

**Comment by rbarrois** [comment]
Thanks! Looks fine by me ;)

**Comment by encukou** [comment]
Tagged and [released to PyPI](https://pypi.python.org/pypi/pyldap/2.4.37).
