### ISSUE TITLE
Install Error Visual studio 2014 dependancy?

### ISSUE THREAD

**Issue by jscull** [pyldap/pyldap#108]
Trying to install via Pip and the package off of the python package index, both routes I get this error: 

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

From this point the install exits and ends.

**Comment by jscull** [comment]
Fixed by installing through whl file found here: http://www.lfd.uci.edu/~gohlke/pythonlibs/

Might want to address the issue in pip fails to build the wheel from dist?

**Comment by hroncok** [comment]
Maybe we could talk to @cgohlke and make those builds available directly from PyPI?

**Comment by jscull** [comment]
I also had issues installing via your setup.py, but all dependencies you listed where met.
