### ISSUE TITLE
Binding with digest-md5 fails right after success

### ISSUE THREAD

**Issue by liquidpele** [pyldap/pyldap#111]
I'm using pyldap 2.4.37 installed via pip on a centOS 6 machine, with openldap 2.4.36

This is is how I'm trying to set up for digest-md5 auth, with the purpose if checking a user's credentials against the AD server for auth in a separate app.  

con = ldap.initialize('ldap://win2k8-ad.my.domain.com:389')
auth1 = ldap.sasl.sasl({ldap.sasl.CB_AUTHNAME: 'someuser', ldap.sasl.CB_PASS: 'thepassword'}, 'DIGEST-MD5')
auth2 = ldap.sasl.sasl({ldap.sasl.CB_AUTHNAME: 'Administrator', ldap.sasl.CB_PASS: 'thepassword'}, 'DIGEST-MD5')

Then, when doing binds, the first one will succeed:
con.sasl_interactive_bind_s("", auth1)
0

But doing it again *always* fails... even when done *right* afterward: 
con.sasl_interactive_bind_s("", auth1)
LDAPError - INVALID_CREDENTIALS: {'info': u'00090313: LdapErr: DSID-0C09052B, comment: AcceptSecurityContext error, data 0, v1772', 'desc': u'Invalid credentials'}

The only way to get it working again, is to bind with auth2, which succeeds... then *that* one always fails but you can then again bind with auth1.  

Further, waiting a while and then trying seems to just start giving "Local error":

LDAPError - LOCAL_ERROR: {'info': u'00090313: LdapErr: DSID-0C09052B, comment: AcceptSecurityContext error, data 0, v1772', 'errno': 107, 'desc': u'Local error'}

**Comment by rbarrois** [comment]
Hmm, I'm unsure: why do you try to bind twice in a row on the same connection?

When you say "waiting a while", how long exactly? You might have reached a timeout on the server.

**Comment by liquidpele** [comment]
The main issue is that creating a new connection doesn't fix it.   If you call ldap.initialize again and try again with the same user, it still fails until you bind with a different one.

**Comment by encukou** [comment]
Please check if this still happens with python-ldap 3.0.0b1, which you can install by:

    pip uninstall pyldap
    pip install --pre --upgrade python-ldap

and report any issues to [the python-ldap tracker](https://github.com/python-ldap/python-ldap/issues).
