### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by ChinaParrot** [pyldap/pyldap#115]
```
 def ldap_reset_uidNumber(self):
        """
        重新设置uid,初始值为2000
        :return: True|None 
        """
        result = None
        try:
            obj = self.ldapconn
            obj.protocol_version = ldap.VERSION3
            retrieveAttributes = None
            searchFilter = 'uid=*'
            searchScope = ldap.SCOPE_SUBTREE
            ldap_result = self.ldapconn.search_s(self.base_dn, searchScope, searchFilter, retrieveAttributes)
            start_uidNumber = 2000
            for onedn in ldap_result:
                 obj.modify_s(onedn[0], [(ldap.MOD_REPLACE, 'uidnumber', [str(start_uidNumber).encode()])])
                 obj.unbind_s()
                 start_uidNumber += 1
                 result = True
        except ldap.LDAPError as e:
            logger.error("%s uidnumber更新失败，原因为: %s" %  str(e))
        return result
```
exec:  obj.modify_s(onedn[0], [(ldap.MOD_REPLACE, 'uidnumber', [str(start_uidNumber).encode()])])
error:
  File "/apps/users/ldap_manage.py", line 335, in ldap_reset_uidNumber
    obj.modify_s(onedn[0], [(ldap.MOD_REPLACE, 'uidnumber', [str(start_uidNumber).encode()])])
  File "lib/python3.5/site-packages/ldap/ldapobject.py", line 600, in modify_s
    return self.modify_ext_s(dn,modlist,None,None)
  File "lib/python3.5/site-packages/ldap/ldapobject.py", line 572, in modify_ext_s
    msgid = self.modify_ext(dn,modlist,serverctrls,clientctrls)
  File "/lib/python3.5/site-packages/ldap/ldapobject.py", line 569, in modify_ext
    return self._ldap_call(self._l.modify_ext,dn,modlist,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/lib/python3.5/site-packages/ldap/ldapobject.py", line 329, in __getattr__
    self.__class__.__name__,repr(name)
AttributeError: SimpleLDAPObject has no attribute '_l'

**Comment by spaceone** [comment]
You are doing a obj.unbind_s() in a loop. Move it after the loop and it's fixed.

**Comment by ChinaParrot** [comment]
@spaceone You are a great god
