### ISSUE TITLE
has no attribute '_l'.

### ISSUE THREAD

**Issue by ChinaParrot** [pyldap/pyldap#116]
When I execute it:

```
 self.ldapconn = ldap.initialize(ldap_uri)
 self.ldapconn.simple_bind_s(self.admin_user, self.admin_password) 

```

Error!SimpleLDAPObject has no attribute '_l'.

**Comment by encukou** [comment]
Please check if this still happens with python-ldap 3.0.0b1, which you can install by:

    pip uninstall pyldap
    pip install --pre --upgrade python-ldap

and report any issues to [the python-ldap tracker](https://github.com/python-ldap/python-ldap/issues).
