### ISSUE TITLE
Is Python 3.2 supported?  pyldap uses missing symbol _PyUnicode_AsUTF8

### ISSUE THREAD

**Issue by akkornel** [pyldap/pyldap#117]
Hello!

It seems like pyldap does not support Python 3.2 (and presumably lower Python 3), because it is using the symbol `_PyUnicode_AsUTF8`.  At least from my perspective, I don't have a need for Python 3.2 or lower.  But still, the README and `setup.py` don't seem to mention that Python 3 needs 3.3 or later, so I wanted to report this!

Here's how I set up a Python 3.2 environment to verify this.  I'm running on macOS 10.12:

```
# If using MacPorts, bring in Python 3.2 and OpenLDAP.
# If not using MacPorts, then this assumes Python 3.2 is `python3.2`,
# and that the OpenLDAP headers are installed in system paths.
sudo port install openldap python32
TMPDIR=$(mktemp -d)
cd $TMPDIR
curl https://pypi.python.org/packages/47/15/7f9aabb1ce09d3dc5ecdff2f5a97e0a47f724fe8e398eff6a88626d0164c/setuptools-5.5.1.tar.gz#md5=86bbbfa732c234535316a7d74a49c6ad | tar -xzf -
curl https://pypi.python.org/packages/e4/3a/43fbf0c2ed567efd409d19968da3f373f83b99831090e3660be937f645a6/pyldap-2.4.37.tar.gz#md5=55b3b39d9c1c7837d80203a04d52c6a1 | tar -xzf -
cd setuptools-5.5.1
python3.2 setup.py build ; python3.2 setup.py install --user
cd ../pyldap-2.4.37

# The next two lines are only needed when MacPorts installed OpenLDAP.
# Otherwise, it tries to use OS LDAP headers, which doesn't work.
sed -i -e 's|library_dirs =|library_dirs = /opt/local/lib|' setup.cfg
sed -i -e 's|include_dirs =|include_dirs = /opt/local/include|' setup.cfg

python3.2 setup.py build ; python3.2 setup.py install --user
cd ..
rm -rf setuptools-5.5.1 pyldap-2.4.37
cd ~
rmdir $TMPDIR
```

The build and install goes fine; the error is triggered when loading `ldap`:

```
Karls-Mac-Mini-9346:~ akkornel$ python3.2
Python 3.2.6 (default, Oct 11 2016, 14:54:14) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/akkornel/Library/Python/3.2/lib/python/site-packages/pyldap-2.4.37-py3.2-macosx-10.12-x86_64.egg/ldap/__init__.py", line 22, in <module>
    import _ldap
ImportError: dlopen(/Users/akkornel/Library/Python/3.2/lib/python/site-packages/pyldap-2.4.37-py3.2-macosx-10.12-x86_64.egg/_ldap.so, 2): Symbol not found: _PyUnicode_AsUTF8
  Referenced from: /Users/akkornel/Library/Python/3.2/lib/python/site-packages/pyldap-2.4.37-py3.2-macosx-10.12-x86_64.egg/_ldap.so
  Expected in: flat namespace
 in /Users/akkornel/Library/Python/3.2/lib/python/site-packages/pyldap-2.4.37-py3.2-macosx-10.12-x86_64.egg/_ldap.so
>>> ^D
```

It seems that `PyUnicode_AsUTF8` is present starting in Python 3.3; it is not listed in the equivalent page for Python 3.2.

https://docs.python.org/3.3/c-api/unicode.html#PyUnicode_AsUTF8
https://docs.python.org/3.2/c-api/unicode.html

In terms of current active releases, I'm guessing that only Debian wheezy would really be affected (it ships with Python 3.2).

**Comment by encukou** [comment]
Right, Python 3.2 is not supported. The end of life for it was [in February 2016](https://www.python.org/dev/peps/pep-0392/#lifespan), so I'd hope no one is using it for anything security-related (unless their distro/vendor provides longer support, of course).

Currently pyldap is [tested](https://github.com/pyldap/pyldap/blob/master/.travis.yml) on 2.7 and 3.3, 3.4, 3.5, 3.6. Pull requests that would make this more obvious are welcome :)

**Comment by hroncok** [comment]
Could be added to classifiers: https://github.com/pyldap/pyldap/blob/master/setup.py#L120

**Comment by akkornel** [comment]
@encukou OK, that is good to know!  My main thought is in case anyone tries to use it on Debian wheezy, which has Python 3.2.  Though yeah, they shouldn't be using wheezy right now anyway…

My code's `setup.py` has a `version_info` check for people running it directly, and also the `python_requires` field is set, which affects people installing my software from wheel (although wheel installation isn't in use here).

I can work up a PR that does both here, although older versions of setuptools do not recognize `python_requires`, and would generate a warning.
