### ISSUE TITLE
errno-related timeout raises non-LDAPError

### ISSUE THREAD

**Issue by malthe** [pyldap/pyldap#124]
In case an `IndexError` is raised `_ldap_call`, the current logic does not re-raise the `LDAPError` but instead the `IndexError` breaking expectations further up.

See d8ac99c3c376ab6d3379b233acb7747db8dedd4f.

**Comment by darkrain42** [comment]
Note that this issue only appears to occur in Python 2 (or, at least, Python 3.6 re-raises the _original_ exception, not the _last_ one).

It seems like there are two possible fixes here:

1. Rewrite the offending `if 'info'...` line to check that `len(args) > 0` (or something as simple as `if e.args and 'info' not in ...`), and then remove the `try` / `except`.

2. Adopt/adapt the [upstream fix](http://python-ldap.cvs.sourceforge.net/viewvc/python-ldap/python-ldap/Lib/ldap/ldapobject.py?r1=1.165&r2=1.166&pathrev=MAIN), but update for Python 3.

Python 3's `raise` syntax is different, and the Python 2 syntax will raise a `SyntaxError` even if you condition it on the Python version. The ideal way to do that would be to have pyldap add a dependency on six and just use [six.reraise](https://pythonhosted.org/six/#six.reraise).

**Comment by encukou** [comment]
I'll adapt upstream fix as soon as I get to merging python-ldap 2.4.45.
