### ISSUE TITLE
   error: Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by acidpassion** [pyldap/pyldap#127]
reading manifest template 'MANIFEST.in'
    warning: no files found matching 'Makefile'
    warning: no files found matching 'Modules\LICENSE'
    writing manifest file 'Lib\pyldap.egg-info\SOURCES.txt'
    running build_ext
    building '_ldap' extension
    error: Unable to find vcvarsall.bat

    I have visual studio 2015 already, not sure why

**Comment by hroncok** [comment]
Try https://stackoverflow.com/a/10558328/1839451

**Comment by tiran** [comment]
You need the right version of VS for your Python version, e.g. VS 2008 for Python 2.7 or VS 2015 for Python 3.5+. python-ldap also depends on several external libraries (OpenLDAP, Cyrus SASL, OpenSSL, Heimdal GSSAPI). I suggest that you grab unofficial Windows builds from https://www.lfd.uci.edu/~gohlke/pythonlibs/ instead.
