### ISSUE TITLE
Precompiled wheels

### ISSUE THREAD

**Issue by stakemura** [pyldap/pyldap#129]
It would be very helpful to have binary wheel packages for UNIX and Windows platform.

I think it might work to build those wheels using Appveyor service: http://www.appveyor.com/

**Comment by tiran** [comment]
We can't have manylinux1 wheels on Linux. The ldap bindings depend on shared libraries that are not part of the manylinux1 standard. I tried to create Linux wheels a while ago, but failed.  The C code does not even compile on CentOS 5 any more, too.

+1 for Windows, patches welcome :)

**Comment by hroncok** [comment]
> The ldap bindings depend on shared libraries that are not part of the manylinux1 standard.

Can we bundle them with `auditwheel repair`?

> The C code does not even compile on CentOS 5 any more, too.

Assuming we'd fix that somehow.

**Comment by hroncok** [comment]
:eye: To anyone looking into this, have a look at https://github.com/joerick/cibuildwheel

**Comment by tiran** [comment]
> Can we bundle them with auditwheel repair?

I don't think that's a good idea. I don't want to bundle an ancient version of libldap with ancient OpenSSL version and broken GSSAPI support.

libldap pulls in OpenSSL or NSS, Kerberos, GSSAPI, SASL, and several additional dependencies:

```
$ ldd /usr/lib64/python2.7/site-packages/_ldap.so  | sort
        /lib64/ld-linux-x86-64.so.2 (0x00007f309d224000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f3099a67000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f309a3d2000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f309c380000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f309ab21000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007f3099236000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f309a185000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f3099c6b000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f3099032000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f3099e9e000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f3099858000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f309c171000)
        libldap_r-2.4.so.2 => /lib64/libldap_r-2.4.so.2 (0x00007f309cdb8000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f309a608000)
        libnspr4.so => /lib64/libnspr4.so (0x00007f309ad25000)
        libnss3.so => /lib64/libnss3.so (0x00007f309b59d000)
        libnssutil3.so => /lib64/libnssutil3.so (0x00007f309b36d000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f3098b97000)
        libplc4.so => /lib64/libplc4.so (0x00007f309af64000)
        libplds4.so => /lib64/libplds4.so (0x00007f309b169000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f309c755000)
        libpython2.7.so.1.0 => /lib64/libpython2.7.so.1.0 (0x00007f309c974000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f309bf57000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f3099439000)
        libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f309bd3a000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f3098e0a000)
        libsmime3.so => /lib64/libsmime3.so (0x00007f309b8c6000)
        libssl3.so => /lib64/libssl3.so (0x00007f309baed000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f309a91e000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f3099641000)
        linux-vdso.so.1 (0x00007ffdd81d6000)
```

**Comment by encukou** [comment]
As the python-ldap maintainer:
* I don't want to publish Linux wheels, for the reasons stated above.
* I'd welcome Appveyor-built Windows wheels, if someone adds the infrastructure. (It does need to be built automatically; in the past python-ldap published hand-built files but those are out of the question for security reasons.)

If you'd like to add this, please open an issue at the [python-ldap tracker](https://github.com/python-ldap/python-ldap/issues). The pyldap project is being merged there.

**Comment by tiran** [comment]
FYI, I tried to build Windows wheels a while ago and failed. OpenLDAP depends on several other projects:

* libdb (formerly known as Berkeley DB or sleepycat)
* OpenSSL
* Heimdal for GSSAPI
* SASL

OpenLDAP for Windows does not ship all dependencies as libs. The libs only contain openldap symbols, not SASL, Heimdal GSSAPI, and OpenSSL
