### ISSUE TITLE
Update to python-ldap 2.5.1

### ISSUE THREAD

**Issue by tiran** [pyldap/pyldap#130]
2.5.1 has been released with fixes for pyasn1 issue (PR #126).

http://python-ldap.cvs.sourceforge.net/viewvc/python-ldap/python-ldap/CHANGES?revision=1.484&view=markup

**Comment by encukou** [comment]
One thing I'm worried about is the "soft" dependency on pyasn1. The fact that python-ldap needs either pyasn1>=0.3.7 *or* no pyasn1 at all is not recorded in a machine-readable way, so it's possible to install python-ldap with an old, incompatible version of pyasn1. And then, at run-time the resulting error isn't very clean.
I'd like to solve that before releasing.

**Comment by tiran** [comment]
Let's add requirements to ``setup.py``.
