### ISSUE TITLE
Cannot import name '__version__'

### ISSUE THREAD

**Issue by clrusby** [pyldap/pyldap#143]
When I run import ldap, I get this error:-

```
----> 9 from pkginfo import __version__, __author__, __license__
     10
     11 import sys

ImportError: cannot import name '__version__'

```
I seem to be able to fix it by changing the code to:-

`from ldap.pkginfo import __version__, __author__, __license__`

which is basically the same as what's happening on line 20 later in the file anyway.

Has anybody else seen this?  If so, should I create a pull request with the fix?

Thanks
Chris

**Comment by encukou** [comment]
Thanks for noticing!
We're merging pyldap back into python-ldap, which [has this issue fixed now](https://github.com/python-ldap/python-ldap/blob/master/Lib/ldap/__init__.py) in the development version. Could you test it and report bugs there?
Sorry for not <del>putting a note here</del> <ins>removing code from here</ins> yet; it should be done by the end of this week.

**Comment by clrusby** [comment]
OK great, will try and do this (am behind a corporate firewall so might take a little while for the wheels to turn).

Could you give an approximate timeline for having a stable version of python-ldap with these changes?  (Basically I'm after a version that supports python 3.)

Thanks
Chris

**Comment by encukou** [comment]
I hope to release python-ldap 3.0 beta next week, and 3.0 final by the end of year. Absolutely no guarantees, though.

**Comment by encukou** [comment]
python-ldap 3.0.0b1 is now released.
This is beta, so when installing with `pip` you'll need the `--pre` option, i.e.:

    pip install --pre python-ldap

Please report any issues on the [python-ldap tracker](https://github.com/python-ldap/python-ldap/issues).
