### ISSUE TITLE
Python-ldap.org is down. Unable to access documentation

### ISSUE THREAD

**Issue by gaelanadams** [pyldap/pyldap#144]
Hello, 

The website https://www.python-ldap.org/ is reporting an incompatible cipher mismatch for TLS.

**Comment by gaelanadams** [comment]
Upon noticing the DEPRECATED banner, please enable python-ldap.org to redirect to https://python-ldap.readthedocs.io/en/latest/

**Comment by tiran** [comment]
I saw ``SSL_ERROR_NO_CYPHER_OVERLAP``, too. It works again for me.

**Comment by encukou** [comment]
Thanks for noticing!
This was, hopefully, only a momentary glitch; let us know if it happens again.

The readthedocs.io page is, basically, a staging area for the future python-ldap.org. I'm in the process of updating everything and aligning with a release, but I now had to rush transferring the DNS domain so there might be glitches.

**Comment by encukou** [comment]
The migration is tracked at https://github.com/python-ldap/python-ldap/issues/1
