### ISSUE TITLE
Release 3.0.0 (as a dummy package)

### ISSUE THREAD

**Issue by encukou** [pyldap/pyldap#146]
python-ldap 3.0.0 is now out; pyldap has fulfilled its purpose.
If no urgent issues are found in python-ldap, I'll release pyldap 3.0.0 (dummy package) this week.
(Or next week, at latest)

**Comment by encukou** [comment]
[Done](https://pypi.python.org/pypi/pyldap/3.0.0).

**Comment by slokhorst** [comment]
Could you also make a release on GitHub (at [releases](https://github.com/pyldap/pyldap/releases)? )

**Comment by encukou** [comment]
[Done](https://github.com/pyldap/pyldap/releases/tag/python-ldap-3.0.0.post1). Sorry for the delay.
