### ISSUE TITLE
Upgrading from pyldap 2.4.45 to 3.0.0 breaks the package

### ISSUE THREAD

**Issue by anx-ckreuzberger** [pyldap/pyldap#148]
Somehow this dummy package breaks things for me when I upgrade from 2.4.45 to 3.0.0 I can no longer use the proper imports.

```bash
~/temp$ virtualenv -p python3 venv
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/ckreuzberger/temp/venv/bin/python3
Also creating executable in /home/ckreuzberger/temp/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...source venv/bin/adone.

~/temp$ source venv/bin/activate
(venv) ~/temp$ pip install "pyldap<3"
Collecting pyldap<3
Requirement already satisfied: setuptools in ./venv/lib/python3.5/site-packages (from pyldap<3)
Installing collected packages: pyldap
Successfully installed pyldap-2.4.45
(venv) ~/temp$ pip install "pyldap>=3" --upgrade
Collecting pyldap>=3
Collecting python-ldap>=3.0.0b1 (from pyldap>=3)
Collecting pyasn1>=0.3.7 (from python-ldap>=3.0.0b1->pyldap>=3)
  Using cached pyasn1-0.4.2-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.1.5 (from python-ldap>=3.0.0b1->pyldap>=3)
  Using cached pyasn1_modules-0.2.1-py2.py3-none-any.whl
Installing collected packages: pyasn1, pyasn1-modules, python-ldap, pyldap
  Found existing installation: pyldap 2.4.45
    Uninstalling pyldap-2.4.45:
      Successfully uninstalled pyldap-2.4.45
Successfully installed pyasn1-0.4.2 pyasn1-modules-0.2.1 pyldap-3.0.0 python-ldap-3.0.0

(venv) ~/temp$ python
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldap
>>> ldap.SCOPE_SUBTREE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ldap' has no attribute 'SCOPE_SUBTREE'
>>> 
```

However, if I create a completely new virtualenv and run ``pip install pyldap`` (which installs version 3.0) it works fine.

For comparison, this is what my site-packages/ldap/ directory looks like when I upgrade:

![screenshot_2018-03-22_08-17-39](https://user-images.githubusercontent.com/18396259/37756369-87b041de-2da9-11e8-892d-ec8e3b9760d7.png)

And this is what it looks like when I run a completely new installation:

![screenshot_2018-03-22_08-18-46](https://user-images.githubusercontent.com/18396259/37756408-aa13ba94-2da9-11e8-99f1-da3d98ea9388.png)

So for some reason separately uninstalling pyldap==2.4.45 and then installing pyldap==3.0.0 (which acts as a dummy package) works, but doing a ``pip install pyldap --upgrade" does not work.

Is there any way to fix this within the ``setup.py`` script?

**Comment by hroncok** [comment]
Oh! I see what happens here.

 1. pyldap 2 has some files
 2. upgrade to pyldap 3 requires python-ldap 3
 3. python-ldap 3 gets installed and overrides some (most) pyldap 2 files
 4. pyldap 2 is uninstalled, removing some (most) python-ldap 3 files thinking they belong to pyldap 2
 5. pyldap 3 gets installed with no files
 6. as a result, files are missing, python-ldap 3 is not working properly

**Comment by anx-ckreuzberger** [comment]
Sounds like it. 
Though the behaviour is weird, as the pip output command clearly states that FIRST pyldap 2 is uninstalled, and then pyldap 3 is installed.

**Comment by hroncok** [comment]
Yes. That's 4 and 5 in that very order.

**Comment by encukou** [comment]
I searched pip issues for this, and sure enough there is one open: https://github.com/pypa/pip/issues/4961

Unfortunately I don't know of a good way to fix this, except tell people to uninstall and re-install :(

**Comment by anx-ckreuzberger** [comment]
Oh well, that sucks :(

Anyway, we now know that there is an issue, so it can be documented in the README?

**Comment by encukou** [comment]
I plan to get to it soon. (PRs are welcome of course.)

**Comment by rbarrois** [comment]
Closing this issue, since the warning has been added and this repository is now archived.
