### ISSUE TITLE
Modlist tuple length mismatch on Python 2

### ISSUE THREAD

**Issue by msimacek** [pyldap/pyldap#15]
When adding entries, modlist attribute is supposed to be a list of 2-tuples, but it internally uses _unbytesify_modlist function, which expects a list of 3-tuples, leading to "Too many values to unpack" error. Happens on Python 2 only, on Python3 the function is a no-op.

**Comment by msrb** [comment]
I am getting slightly different error message, but I believe that the root cause is the same. I will prepare PR.

**Comment by msimacek** [comment]
I already have a simple modification [1] that should fix this particular problem, but I'm getting other errors down the road, so I'm not sure, whether more modifications aren't needed
[1] https://github.com/msimacek/pyldap/commit/c75bdfd6c764299239d206adc51db06f9a28b89d

**Comment by msrb** [comment]
The fix looks OK in my opinion, I created basically the same yesterday. In any case, if you're working on it, then please let others know. We clearly duplicated work on this one.
