### ISSUE TITLE
LDIF parsing breaks on empty values without trailing space

### ISSUE THREAD

**Issue by msimacek** [pyldap/pyldap#17]
Parsing LDIF with with empty values, such as:

```
attr:
```

without trailing space after colon results in

```
UnboundLocalError: local variable 'attr_value' referenced before assignment
```

**Comment by encukou** [comment]
I believe this occurs in python-ldap as well.

**Comment by msimacek** [comment]
It occurs during freeipa installation, so it's not yet in Fedora (it didn't crash for me before updating to pyldap). Seems to be introduced by 65cc6fdb (I don't know how it maps to upstream commits)

**Comment by encukou** [comment]
Closed by https://github.com/pyldap/pyldap/pull/22
