### ISSUE TITLE
I'd love if pyldap provided a mockldap as well

### ISSUE THREAD

**Issue by Callek** [pyldap/pyldap#18]
There is https://bitbucket.org/psagers/mockldap/issues/11/installation-with-python-3#comment-20789775 which addresses that thought, without this though I still have a hard dep on python-ldap(py2) on my codebase :(

**Comment by encukou** [comment]
Hi,
We'd like merge pyldap back into python-ldap at one point, and adding new features that aren't in python-ldap wouldn't help that goal.
Do you think including mockldap in python-ldap would be a good idea?

**Comment by Callek** [comment]
I was more thinking a seperate library that forked mockldap to use pyldap instead that could be uploaded to pypi. So that requirements files could specify mockpyldap for testing in py3, along with pyldap. (otherwise mockldap requires python-ldap which can't be installed in py3)

**Comment by encukou** [comment]
pyldap is a continuation of Raphaël' unofficial `py3` branch, on which mockldap apparently depends now. Hopefully the maintainer of mockldap itself can be convinced to switch to pyldap, at least under py3.

I've opened https://github.com/rbarrois/python-ldap/pull/14 to make the succession "official" for users of Raphaël's py3 branch. I've also commented on the issue you linked above.

**Comment by encukou** [comment]
Since this is an issue for either mockldap or a new mockpyldap project, but not pyldap itself, I'm closing it.
