### ISSUE TITLE
Define upgrade path from upstream's python-ldap

### ISSUE THREAD

**Issue by rbarrois** [pyldap/pyldap#2]
The upstream version uses the name `ldap`.

Two options here:
- Keep the name
- Install under `pyldap`

**Keeping the name**:
- Requires backwards compatibility
- Eases merging back upstream
- Prevents users from having both versions side by side

**Using another name**:
- Allows for updated APIs
- Allows two versions living in the same system
- Requires shuffling files around and lots of useless renames

**Comment by tiran** [comment]
Good point! The issue would have deserved #1. The bigger question is: What is our goal. Are we truly planning an autonomous fork of python-ldap or should this project just act as an incubator for Python 3 support that will be merged back into upstream python-ldap? Should we modernize and clean up the code to a PEP 8 compatible modern style or should we try to reach our goals with little changes as possible?

I like to strive for the 1st option in both cases. I don't want to alienate upstream developers and rather have them on board. With tools like virtualenv it is also easy to install and test pyldap as an alternative to python-ldap. I like to keep the API as close to python-ldap as possible, too. We at Red Hat use python-ldap in large projects such as FreeIPA and OpenStack. API stability makes our lives easier.

PS: If the name is changed, then ldif, dsml and ldapurl should be moved into the pyldap name space, too.

**Comment by rbarrois** [comment]
@tiran I agree — this question is quite important.

I'd rather work with upstream — I think the absence of support for Python3 comes from lack of time to investigate the issue _and_ a lack of a clear description of the required changes.

However, I'd love to see a few improvements to the codebase — and I'm afraid some might be considered breaking changes.

Thus, two options at this time:
- We advance the project at a level we deem sufficient, then submit it back to the mailing-list
- We contact Michael Ströder (current maintainer) and ask for its opinion

I'd rather go for the second opinion, once we get a proper view of goals for this project.

**Comment by rbarrois** [comment]
So, let's go for possible goals:
- Py3 compatibility (the main one, from my point of view)
- Code cleanup (PEP8 consistency, mainly)
- Modern tooling and best practices (unit tests, continuous integration, better docs, ...)
- Easier contribution (beware Contributor License Agreements though)

What else would you people want to see?

**Comment by encukou** [comment]
Sounds good; I'd add one more:
- Try to merge back into python-ldap

I still hope Michael Ströder will articulate his opinions on this, later.

**Comment by hroncok** [comment]
So apparently, Michael want a rewrite, which is maybe a good thing, but it will take much time. https://mail.python.org/pipermail/python-ldap/2015q3/003560.html

Maybe we might define the strategy here as a thing that happens in the meantime and consider merging this back to upstream as a no go.

**Comment by tiran** [comment]
I also think that a rewrite is going to a long time, probably one year or even years. We need a working LDAP adapter for Python 3 in a matter of weeks in order to start porting software to Python 3. The LDAP library doesn't have to be production grade from the beginning. I'm also unsure if a rewrite is the best idea (Netscape anyone?).

**Comment by rbarrois** [comment]
@tiran @hroncok I agree that a rewrite is not the best idea right now.

I propose the following plan:
- `pyldap` versions 2.X follow `python-ldap`, with Py3 support and backwards compatibility toggles
- If a rewrite occurs, it would start numbering at 3.X

**Comment by hroncok** [comment]
:+1:

**Comment by encukou** [comment]
FWIW, a total rewrite is for example here: https://pypi.python.org/pypi/ldap3/

It's not what Michael wanted by "rewrite", but – if I take it *ad absurdum* – no one but Michael can build exactly what he wants :(

**Comment by encukou** [comment]
pyldap is merged into python-ldap 3.0.0.
An upgrade guide is at http://python-ldap.readthedocs.io/en/latest/bytes_mode.html
