### ISSUE TITLE
Release new version to pypi

### ISSUE THREAD

**Issue by stakemura** [pyldap/pyldap#27]
Is there the plan to release a new version to Pypi once some fix were added in the near future?

**Comment by encukou** [comment]
Yes.

The  2.4.23 release of `python-ldap` was a bit rushed; `search_ext` will fail when `attrlist=None`. A proper fix landed today on the python-ldap mailing list. Waiting until it is applied there.

**Comment by encukou** [comment]
Pull request: #28

**Comment by rbarrois** [comment]
That's online :)
