### ISSUE TITLE
Release on PyPI

### ISSUE THREAD

**Issue by hroncok** [pyldap/pyldap#3]
Once we make decisions about design issues, it would be great to have a release of pyldap on PyPI.

Assigning @rbarrois, as he has the rights to do it (owns pyldap on PyPI).

**Comment by encukou** [comment]
It would be nice to release after design issues are solved, but not wait for smaller bugfixes, so that users can start porting & testing as soon as possible.

**Comment by hroncok** [comment]
I would say merge and close #1, do not merge #2 and we can do a release on pypi, so others can start to easily use pyldap and report problems.

**Comment by hroncok** [comment]
@rbarrois, could you please do the release today?

**Comment by rbarrois** [comment]
Here you go: https://pypi.python.org/pypi/pyldap/

**Comment by hroncok** [comment]
Awesome, thank you.
