### ISSUE TITLE
Version numbering for pyldap fix releases?

### ISSUE THREAD

**Issue by rbarrois** [pyldap/pyldap#37]
We have a clear policy for version numbering from upstream versions.

However, how should we number releases that fix bugs in our fork, thus happening between upstream releases?

Should we go with `(upstream).1` for our first bugfix on top of an upstream version?
For instance, the fixes on `2.4.25` would be in `2.4.25.1`. This seems compatible with PEP440 (https://www.python.org/dev/peps/pep-0440/).

What do you think?

**Comment by hroncok** [comment]
As long as upstream dos not use those and it's compatible with the PEP, I'm OK with it.

**Comment by encukou** [comment]
Yeah, that sounds good.

**Comment by rbarrois** [comment]
OK, great!

I suggest to release `2.4.25.1` with the fix for `ldap.add_ext` on Python2.
Is that fine with you?

**Comment by encukou** [comment]
Definitely. Thanks for making the time!

**Comment by rbarrois** [comment]
Great, all done.

I'll update the wiki accordingly.
