### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by hroncok** [pyldap/pyldap#41]
Should we add CONTRIBUTING.md with some explanation similar to  https://github.com/pyldap/pyldap/pull/40#issuecomment-215408675?

**Comment by encukou** [comment]
Yes. Perhaps also a note in README saying the list of goals there is exhaustive.

**Comment by encukou** [comment]
python-ldap now has [CONTRIBUTING.rst](https://github.com/python-ldap/python-ldap/blob/master/CONTRIBUTING.rst), which links to [comprehensive docs](http://python-ldap.readthedocs.io/en/latest/contributing.html). All shiny!
