### ISSUE TITLE
using pyldap with ldappool

### ISSUE THREAD

**Issue by stevemar** [pyldap/pyldap#42]
Thanks for your work with this project! I had a hopefully quick question.

Our project (https://github.com/openstack/keystone) currently uses python-ldap and we're looking to make it python3 compatible. pyldap seems like the logical choice, but there is one hiccup in the plan. We currently also use ldappool (https://pypi.python.org/pypi/ldappool/) to pool connections, we've received positive feedback that this does help improve performance and would like to keep using ldappool (or a similar mechanism). Do you know if we could use pyldap with ldappool? Or have an alternate suggestion? Have you had similar requests for this feature before? Thanks in advance!

**Comment by encukou** [comment]
`pyldap` tries to be a straightforward fork; patches not related to Python 3 porting or project infrastructure go to `python-ldap`.
A tool like `ldappool` will probably need a bit of porting effort to make sure text/bytes show up at the right places, but the changes should not beinvasive, and hopefully ldaptools's maintainers will accept them.

**Comment by rbarrois** [comment]
Hi,

`ldappool` doesn't look quite maintained; however, adapting it to support `pyldap`'s `byte_mode` parameter should be rather easy ; if you wish to bring that feature there, I can help you craft the adequate pull request :)

**Comment by encukou** [comment]
I see ldappool 2.0.0 requires pyldap. If there are any issues, please open them separately.
