### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by Akasurde** [pyldap/pyldap#46]
I would like to see pyldap source PEP8 compliant. Let me know everyone views on this.

**Comment by encukou** [comment]
`pyldap` is a fork of `python-ldap`, and we hope to merge the changes back to python-ldap if the original author allows it. Non-functional changes in the code would complicate the merge.
So, changes not related to porting or project infrastructure should be done in there, and discussed on the [python-ldap mailing list](https://mail.python.org/mailman/listinfo/python-ldap).

(Leaving open until a link to python-ldap discussion is added here.)

**Comment by Akasurde** [comment]
@encukou OK Petr, I agree with you.

**Comment by encukou** [comment]
If you start a conversation there, you can link it here and re-open the issue.
