### ISSUE TITLE
ldif type can't accept byte values

### ISSUE THREAD

**Issue by Firstyear** [pyldap/pyldap#49]
py.ldap returns all attribute values as bytes.

However, if you wanted to feed these into ldif.LdifWriter, when you attempt to use unparse on this, it fails.

```
  File "/usr/lib/python3.5/site-packages/lib389/_entry.py", line 269, in __repr__
    sio, Entry.base64_attrs, 1000).unparse(self.dn, newdata)
  File "/usr/lib64/python3.5/site-packages/ldif.py", line 212, in unparse
    self._unparseAttrTypeandValue('dn', dn)
  File "/usr/lib64/python3.5/site-packages/ldif.py", line 150, in _unparseAttrTypeandValue
    if self._needs_base64_encoding(attr_type,attr_value):
  File "/usr/lib64/python3.5/site-packages/ldif.py", line 139, in _needs_base64_encoding
    not safe_string_re.search(attr_value) is None
TypeError: cannot use a string pattern on a bytes-like object

```

Given that pyldap returns bytes, one would expect the other pyldap types to be able to handle values being fed through the api in different parts as bytes.

**Comment by Firstyear** [comment]
Related to https://github.com/pyldap/pyldap/pull/47

**Comment by encukou** [comment]
Might be the same issue as https://github.com/pyldap/pyldap/pull/50.
If you can still reproduse this, could you share the offending ldif?

**Comment by encukou** [comment]
Please reopen if you can still reproduce this.
