### ISSUE TITLE
Latest pyldap version does not work with python 2.7.11

### ISSUE THREAD

**Issue by sunilkatwal** [pyldap/pyldap#59]
2.4.25.0 version works fine with python 2.7.11  but does not work with latest version 2.4.25.1.
There is no issue with python 2.7.5 version.

**Comment by hroncok** [comment]
Could you please elaborate on "does not work"? What do you do, what happens, what should happen instead? Thanks

**Comment by sunilkatwal** [comment]
We have mainly work with two version of python 2.7.5 and 2.7.11. The 2.7.5 version is installed via Redhat installer and 2.7.11 package is installed from python.

When we try to print the result for `results = ld.search_s(basedn, ldap.SCOPE_SUBTREE, filter, ['distinguishedName'])` using the pyldap, it works fine with 2.7.5 but throws some wierd output with 2.7.11.

With pyldap 2.5.25.1 and python 2.7.5 => it works fine 
With pyldap 2.5.25.1 and python 2.7.11 => 

``` python
[('C\x00N\x00=\x00g\x00s\x003\x00u\x00n\x00i\x00x\x00,\x00O\x00U\x00=\x00U\x00n\x00i\x00x\x00G\x00r\x00o\x00u\x00p\x00s\x00,\x00O\x00U\x00=\x00C\x00o\x00m\x00p\x00u\x00t\x00e\x00r\x00 \x00C', {}),
(None, ['l\x00d\x00a\x00p\x00:\x00/\x00/\x00F\x00o\x00r\x00e\x00s\x00t\x00D\x00n\x00s\x00Z\x00o\x00n\x00e\x00s\x00.\x00j\x00d\x00n\x00e\x00t\x00.\x00d\x00e\x00e\x00r\x00e\x00.\x00c\x00o\x00m\x00/\x00D\x00C\x00']),
(None, ['l\x00d\x00a\x00p\x00:\x00/\x00/\x00D\x00o\x00m\x00a\x00i\x00n\x00D\x00n\x00s\x00Z\x00o\x00n\x00e\x00s\x00.\x00j\x00d\x00n\x00e\x00t\x00.\x00d\x00e\x00e\x00r\x00e\x00.\x00c\x00o\x00m\x00/\x00D\x00C\x00']),
(None, ['l\x00d\x00a\x00p\x00:\x00/\x00/\x00j\x00d\x00n\x00e\x00t\x00.\x00d\x00e\x00e\x00r\x00e\x00.\x00c\x00o\x00m\x00/\x00C\x00N\x00=\x00C\x00o\x00n\x00f\x00i\x00g\x00'])
]
```

But the same code works fine with pyldap 2.4.25.0 version on both python version.

We tried to debug replacing the ldapobject.py from 2.4.25.1 to 2.4.25.0 version and it worked fine.
Not sure why it is not working with the latest pyldap version using 2.7.11 python version.

EDIT by @hroncok, added the above snipped with `\x00`s removed:

``` python
[('CN=gs3unix,OU=UnixGroups,OU=Computer C', {}),
(None, ['ldap://ForestDnsZones.jdnet.deere.com/DC']),
(None, ['ldap://DomainDnsZones.jdnet.deere.com/DC']),
(None, ['ldap://jdnet.deere.com/CN=Config'])
]
```

**Comment by hroncok** [comment]
> We tried to debug replacing the ldapobject.py from 2.4.25.1 to 2.4.25.0 version and it worked fine.

In that case, this commit might be to blame: https://github.com/pyldap/pyldap/commit/3e2d88996c03bf1ed9eef819a4f27c35846787da

**Comment by hroncok** [comment]
Reading the commit I don't see how that's likely. Could you please share the diff between the `ldapobject.py` you had and the one you replaced it with?

**Comment by encukou** [comment]
I'll close this. Feel free to reopen with the needed information.
