### ISSUE TITLE
Forks and branches

### ISSUE THREAD

**Issue by tiran** [pyldap/pyldap#6]
I like to raise the issue of forks and branches. pyldap is a fork my fork, which I forked from Raphaël's personal git repos, which itself is yet another fork of a CVS repository. A couple of branches are involved, too. It's too confusing.

I like to restart with a clean slate and remove my fork out of the picture. We also should come with a plan how to pull updates from upstream's CVS. Git's cvs importer can pull updates from CVS as long as the CVS import branch contains **only** CVS commits.
## suggestions
- have a dedicated `cvs` branch that contains only CVS commits. In both Raphaël's and my repository that's is currently the `master` branch. Action: rename `master` to `cvs`.
- new development happens in `master`. Let's rename the `py3` branch to `master`.
- regularly pull changes from CVS into the `cvs` branch and rebase master

```
git cvsimport -d:pserver:anonymous@python-ldap.cvs.sourceforge.net:/cvsroot/python-ldap python-ldap -o cvs
```

**Comment by hroncok** [comment]
I agree with your suggestions.

**Comment by rbarrois** [comment]
@tiran OK for most of it; what about renaming to `upstream` instead of `cvs`?

Beyond that, merging `csv` (or `upstream`) into `master` might be easier than rebasing — especially if other repos are forked from this one.

**Comment by encukou** [comment]
Yes, if other people base their work on pyldap, it would be much easier to merge rather than rebase.

**Comment by encukou** [comment]
I've documented this on the [wiki](https://github.com/pyldap/pyldap/wiki), with merging rather than rebasing.

**Comment by hroncok** [comment]
Also detached this repo, it's no longer a fork.
