### ISSUE TITLE
*** TypeError: ('expected a string in the list',..

### ISSUE THREAD

**Issue by sivanbecker** [pyldap/pyldap#68]
Hi,

i'm working on a tool web based (only backend) that will handle all dhcp/ldap stuff in the place i work. i've encountered this error when trying to add a new entry to ldap.
i know that with python2 and python-ldap this code works fine. but i'm trying to implement the same with pyldap and python3.

the error i get is: "*** TypeError: ('expected a string in the list', <the value here changes each time i run this>)

the line of code i'm running and that fails:
```
current_app.ldap_obj.add_s(self.dn(), modlist.addModlist(self.modlist()))
```
where:

* **current_app.ldap_obj** is ldap.ldapobject.SimpleLDAPObject

* **self.dn()** = 'cn=h1,cn=testgroup1,ou=Groups,cn=DHCP Config,cn=dhcpsrv,dc=dhcpawn,dc=net'
***modlist.addModlist(self.modlist())** = [('objectClass', ['dhcpHost', 'top']), ('cn', 'h1'), ('dhcpHWAddress', ['ethernet 00:01:C0:0E:9D:e8'])]

in this case this is the exact exception i get:
*** TypeError: ('expected a string in the list', 'dhcpHost')

please let me know if you need mode data from me, i'd love to get some help here.

thanks
Sivan

**Comment by sivanbecker** [comment]
update : tried to run add_s example from https://github.com/pyldap/pyldap/blob/master/Demo/simple.py and i get the same error.

**Comment by xor-xor** [comment]
@sivanbecker - I came here because of the same error - converting values to lists of bytestrings (as per https://github.com/pyldap/pyldap/issues/48) helped me, so maybe it will help you as well.

**Comment by rbarrois** [comment]
@sivanbecker The LDAP values may be any kind of data (pictures, bytes, etc.); thus, we enforce a "bytes" type.
Thus, you should pass properly encoded values instead of text — ``b'dhcpHost', b'top'``.

The proper value for your modlist would be:

```python
[
    ('objectClass', [b'dhcpHost', b'top']),
    ('cn', [b'h1']),
    ('dhcpHWAddress', [b'ethernet 00:01:C0:0E:9D:E8']),
]
```

If you're sure that every value is text, you could use:
```python
modlist = [
    (field, [value.encode('utf-8') for value in values])
    for field, value in modlist
]
```

Or, you could (and should!) alter the code in ``self.modlist()`` to cast the values to their proper type.

**Comment by sivanbecker** [comment]
Guys ( @xor-xor , @rbarrois ),

thanks a lot for your quick answer. i fixed my code and i'm back on the track :)
one thing - i read issue #48 and saw that #51 emerged from it and closed after merging as if the error message was fixed but i got the same problematic error message.
did i miss something here ? was it fixed ? 
maybe the c code was updated but new version was not compiled ?

**Comment by xor-xor** [comment]
> did i miss something here ? was it fixed ?

I guess that you use the latest version from pypi (i.e. 2.4.25.1), which doesn't contain #51.

**Comment by sivanbecker** [comment]
you are absolutely right.
should i use other version ? how do i know which version includes this fix ?

(i'm learning as you can understand :))

**Comment by xor-xor** [comment]
Well, it's simple - the last release of pyldap is from 2016-03-10 (see: https://github.com/pyldap/pyldap/releases), while #51 got merged on 2016-06-14 - hence no version has this fix (yet) :wink: 

But anyway, #51 doesn't influence pyldap's behavior (apart from changing the contents of the error message), so I guess you can safely continue with 2.4.25.1, while keeping in mind what @rbarrois wrote re: bytes type.

**Comment by sivanbecker** [comment]
will do, thanks :)
