### ISSUE TITLE
test_modlist.py is not run with tox

### ISSUE THREAD

**Issue by hroncok** [pyldap/pyldap#71]
Quote from #70:

> Note that this already has a test (test_modlist.py) that picked this up,
but its not a standard python unittest so isn't run by default.

There are other possible tests that are not unittests and are not run.

**Comment by hroncok** [comment]
I can see it here https://github.com/pyldap/pyldap/blob/pyldap-2.4.25.1/tox.ini#L13

    {envpython} {toxinidir}/Tests/Lib/ldap/test_modlist.py

**Comment by hroncok** [comment]
cc @bbaetz

**Comment by hroncok** [comment]
From the [Travis CI log](https://travis-ci.org/pyldap/pyldap/jobs/186693129):

```
py35 runtests: commands[6] | /home/travis/build/pyldap/pyldap/.tox/py35/bin/python /home/travis/build/pyldap/pyldap/Tests/Lib/ldap/test_modlist.py
Testing function addModlist():
addModlist({'sn': ['StrÃ¶der'], 'objectClass': ['person', 'pilotPerson'], 'dummy3': [''], 'cn': ['Michael StrÃ¶der', 'Michael Stroeder'], 'dummy2': ['2'], 'dummy1': []}) returns
[('cn', ['Michael StrÃ¶der', 'Michael Stroeder']), ('dummy1', []), ('dummy2', ['2']), ('dummy3', ['']), ('objectClass', ['person', 'pilotPerson']), ('sn', ['StrÃ¶der'])]
instead of
[('cn', ['Michael StrÃ¶der', 'Michael Stroeder']), ('dummy2', ['2']), ('dummy3', ['']), ('objectClass', ['person', 'pilotPerson']), ('sn', ['StrÃ¶der'])].
Testing function modifyModlist():
```

There might be a problem that the test fails but does not indicate it in the exit status.

**Comment by encukou** [comment]
I've asked on the python-ldap list if this should be fixed there.

**Comment by hroncok** [comment]
Just for the reference:

> Petr Viktorin wrote:
> > These tests:
> > 
> > Tests/Lib/ldap/schema/test_tokenizer.py
> > Tests/Lib/ldap/test_modlist.py
> > Tests/Lib/test_ldapurl.py
> > 
> > only signal failure by printing to stdout. This makes them cumbersome to run
> > automatically.
> > Is there a reason for this behavior?
> 
> Ancient historic artefacts before automated testing got normal. ;-)
> 
> > Would you accept a patch that converts them to unittest and adds them to
> > runtests.sh?
> 
> Yes.
> 
> Ciao, Michael [Ströder].

[link](https://mail.python.org/pipermail/python-ldap/2017q1/003856.html)

**Comment by bbaetz** [comment]
Yep, I was running these tests manually.

**Comment by encukou** [comment]
This has low priority for me, so it'll take some time, but I'm starting.

**Comment by tiran** [comment]
I'm seeing 

```
test_addModlist (Tests.t_ldap_modlist.TestModlist) ... ok
test_modifyModlist (Tests.t_ldap_modlist.TestModlist) ... ok
```

in output of ``tox``. Closing as fixed
