### ISSUE TITLE
ldap.schema.tokenizer.split_tokens() performance issue

### ISSUE THREAD

**Issue by tiran** [pyldap/pyldap#85]
The function ```split_tokens``` https://github.com/pyldap/pyldap/blob/master/Lib/ldap/schema/tokenizer.py#L10 is causing major performance issues in FreeIPA. After profiling a bunch of different requests and merging the performance stats, ```split_tokens``` sticks up as second most time consuming function in FreeIPA. Nearly a quarter of the total request time of 24 distinct JSON RPC requests is spent in that function. A more detailed analysis is available in FreeIPA ticket https://fedorahosted.org/freeipa/ticket/6679

I like to explore how we could improve the function. I have some ideas (rewrite, regular expression, Cython) but I haven't grokked the tokenizer yet.

**Comment by encukou** [comment]
This should be done in `python-ldap` first – there are still hopes to merge `pyldap` back one day.

**Comment by tiran** [comment]
Thanks, I'll try to find some time to contact upstream.

**Comment by tiran** [comment]
For the record, this implementation with a regular expression is about 7 to 8 times faster. I verified it against > 3,000 schema lines from FreeIPA / 389-DS.

```
import re

# either any string that does not contain $, single quote or white space
# or any string that starts and ends with a single quote (non-greedy match)
tokens_findall = re.compile(r"[^'$\s]+|'.+?'").findall

def split_tokens_fast(s, ignored=None):
    parts = []
    for part in tokens_findall(s):
        # If it starts with a quote, it must end with a quote.
        if part and part[0] == "'":
            part = part[1:-1]
        parts.append(part)
    return parts
```

**Comment by tiran** [comment]
Performance improvement has landed in upstream, http://python-ldap.cvs.sourceforge.net/viewvc/python-ldap/python-ldap/Lib/ldap/schema/tokenizer.py?revision=1.15&view=markup

**Comment by tiran** [comment]
My patch is in upstream release 2.4.33, https://pypi.python.org/pypi/python-ldap/2.4.33

**Comment by encukou** [comment]
2.4.35 is [tagged](https://github.com/pyldap/pyldap/releases) and on [PyPI](https://pypi.python.org/pypi/pyldap).
