### ISSUE TITLE
Cant modify ldap objects if using pyldap

### ISSUE THREAD

**Issue by alexandrezia** [pyldap/pyldap#88]
I'm having an issue updating objects in my Ldap server
Openldap-2.4.40
CentOS 7

Server is refusing to modify objects if using pyldap, however it works if using python-ldap
Using pyldap==2.4.28

Seems like modlist.modifyModlist() from pyldap is not generating the correct output

The following script generates the modification list to be used by modify_s()
```
cat << _EOF_ > modifyModlist-test.py
import ldap
from ldap import modlist
import pprint
pp = pprint.PrettyPrinter(indent=4)
old = {'description': 'Old Description Test'}
new = {'description': 'New Description Test'}
ldif = modlist.modifyModlist(old, new)
pp.pprint(ldif)
_EOF_
```

Usig pyldap:
```
cd /tmp
virtualenv pyldap-env
. pyldap-env/bin/activate
pip install pyldap
python2 modifyModlist-test.py
deactivate
```
will produce: 
```
[   (1, 'description', None),
    (   0,
        'description',
        [   'N',
            'e',
            'w',
            ' ',
            'D',
            'e',
            's',
            'c',
            'r',
            'i',
            'p',
            't',
            'i',
            'o',
            'n',
            ' ',
            'T',
            'e',
            's',
            't'])]
```
which raises an error in my server, as you can see it generates a list for the 'description' value, and my ldap server thinks I'm trying to insert several description values, one for each member of the list.

However, using python-ldap it generates a different output:
```
cd /tmp
virtualenv python-ldap-env
. pyldap-env/bin/activate
pip install python-ldap
python2 modifyModlist-test.py
deactivate
```
will produce
```
[(1, 'description', None), (0, 'description', 'New Description Test')]
```
Whis is accepted by my server.

**Comment by encukou** [comment]
LDAP attributes generally hold sets of values, which pyldap represents as lists. Please use:

    old = {'description': ['Old Description Test']}
    new = {'description': ['New Description Test']}

It should also work in python-ldap.
Does that help?

**Comment by alexandrezia** [comment]
Thanks a lot, it worked.
