### ISSUE TITLE
Errno regression in 2.4.35 python-ldap

### ISSUE THREAD

**Issue by antonc42** [pyldap/pyldap#90]
Regression in python-ldap v2.4.35 has been carried over to pyldap v2.4.35.

See: https://mail.python.org/pipermail/python-ldap/2017q2/003892.html

python-ldap fix: http://python-ldap.cvs.sourceforge.net/viewvc/python-ldap/python-ldap/Lib/ldap/ldapobject.py?r1=1.160&r2=1.162&pathrev=MAIN

**Comment by balacuit** [comment]
:+1: seeings this problem as well

**Comment by akkornel** [comment]
I'm hitting the same bug.  It appears to be fixed in python-ldap 2.4.36, and their current version is 2.4.38.

**Comment by encukou** [comment]
The fix is in python-ldap 2.4.37, not 2.4.36.

python-ldap 2.4.36 contains a rather large refactoring of the tests; it's taking longer than usual to merge it. So, I'll release pyldap 2.4.35.1 with the fix.

**Comment by encukou** [comment]
Released to [PyPI](https://pypi.python.org/pypi/pyldap/2.4.35.1).

**Comment by akkornel** [comment]
Awesome, thank you very much!

**Comment by antonc42** [comment]
Works great, thanks!
