### ISSUE TITLE
Python 3.6.1 error Modules/errors.h:8:18: fatal error: lber.h: No such file or directory

### ISSUE THREAD

**Issue by ChinaParrot** [pyldap/pyldap#91]
Python 3.6.1 version : 
 python3 setup.py build

building '_ldap' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=2.4.35 -IModules -I/usr/include -I/usr/include/sasl -I/usr/local/include -I/usr/local/include/sasl -I/usr/local/include/python3.6m -c Modules/LDAPObject.c -o build/temp.linux-x86_64-3.6/Modules/LDAPObject.o
In file included from Modules/LDAPObject.c:9:0:
Modules/errors.h:8:18: fatal error: lber.h: No such file or directory
 #include "lber.h"
                  ^
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by rbarrois** [comment]
Have you installed the LDAP headers?

See the python-ldap installation instructions: https://www.python-ldap.org/doc/html/installing.html

You might need the "development headers" for openldap for your distribution — typically ``-dev`` packages on Debian/ubuntu.

**Comment by ChinaParrot** [comment]
OK ，centos request ：  yum -y install openldap-devel

**Comment by rbarrois** [comment]
@jqlinux it looks like you've found a solution for this, so I'll close the issue.

If this was a mistake, please reopen it ;)

**Comment by ryangallen** [comment]
and for alpine: `apk add openldap-dev`

**Comment by encukou** [comment]
@ryangallen, would you be willing to provide the *entire* list of development packages for builting & testing on alpine, which we could use in [python-ldap development documentation](http://python-ldap.readthedocs.io/en/latest/installing.html#build-prerequisites)?
python-ldap is where pyldap development continues.
