### ISSUE TITLE
Please tag python-ldap-2.4.38

### ISSUE THREAD

**Issue by akkornel** [pyldap/pyldap#92]
Hello!

I was looking at the `cvs` branch, and the tags, and I noticed that all of the commits for python-ldap version 2.4.38 have been imported, but the tag is missing.

Would you please tag commit 19e21dd11da800da32748791ac26a3c275ee3b98 as `python-ldap-2.4.38`?

Thanks much!

**Comment by encukou** [comment]
I was planning to do that when `pyldap` 2.4.38 would be released, so that GitHub won't tag `python-ldap-2.4.38` as the latest release here. Generally, if you want `python-ldap`, it's better to get it directly from the `python-ldap` project.

What's your use case for needing the tag?

**Comment by akkornel** [comment]
Welp, that was new information to me!  I'm kindof surprised that GitHub doesn't let you explicitly say which tag is the latest release.

Anyway, given that information, please disregard my request.  Thanks much!
